# This file configures the build and deployment settings for Netlify.
[build]
  # Vite's build command.
  command = "npm run build"
  # Vite's default output directory is 'dist'.
  publish = "dist"
  # The directory for our serverless backend functions.
  functions = "netlify/functions"

# This section configures the function bundling.
[functions]
  # Use the esbuild bundler for better performance and compatibility.
  node_bundler = "esbuild"

# --- ADD THIS SECTION ---
# This official Netlify plugin automatically finds and installs dependencies
# listed in any package.json file inside your functions directory.
# This is the definitive fix for the "Cannot find module" error.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# This rule ensures that API calls from the frontend (e.g., /api/like-bot)
# are correctly routed to the serverless function in production.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
