# This file configures the build and deployment settings for Netlify.
[build]
  # Vite's build command.
  command = "npm run build"
  # Vite's default output directory is 'dist'.
  publish = "dist"
  # The directory for our serverless backend functions.
  functions = "netlify/functions"

# This section configures the function bundling.
[functions]
  # Use the esbuild bundler for better performance and compatibility.
  node_bundler = "esbuild"
  # We are removing the 'external_node_modules' line to let the nested
  # package.json handle the puppeteer-core dependency directly.

# This rule ensures that API calls from the frontend (e.g., /api/like-bot)
# are correctly routed to the serverless function in production.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
